services:
  db:
    image: timescale/timescaledb:2.13.0-pg15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: alphadrift
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
  alphadrift:
    build: .
    environment:
      - DB_URL=postgres://...
    depends_on: [db, driftbrain]
  driftbrain:
    build: python-quant/
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgres://...
    depends_on:
      - db
