name: Node CI
on:
  push:
    paths:
      - 'src/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'jest.config.js'
      - '__tests__/**'
  pull_request:
    paths:
      - 'src/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'jest.config.js'
      - '__tests__/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install deps
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test -- --coverage
